### ISSUE TITLE
Implement a basic rendering system

### ISSUE THREAD

**Issue by LeNitrous** [vignetteapp/sekai#3]
As our rendering engine is primarily for 3D, we'd need a basic rendering system that shows 3D models with lighting and shadows.

**Comment by sr229** [comment]
Implemented data structures for Camera and Entity-based transforms via #32. Veldrid integration and the Graphics abstractions are still WIP.

**Comment by LeNitrous** [comment]
Closed via https://github.com/vignetteapp/sekai/commit/de8096bb04ad9085cd34474ad6830fbc6f19e571
