### ISSUE TITLE
Implement UI

### ISSUE THREAD

**Issue by sr229** [vignetteapp/sekai#35]
(Unfortunately?) This may be delayed to Alpha 2, but it depends if our velocity will  not be impacted. 

Essentially we will be implementing a W3C-compliant user interface engine based on [AngleSharp](https://github.com/AngleSharp/AngleSharp) and [ImageSharp](https://github.com/SixLabors/ImageSharp), rendered and backed by our rendering backend. This allows @vignetteapp/web to help with the UI.

Our primary goal is to allow a Blazor-like API, which in turn, would allow us to write the ClearScript objects for it in scripting. Unfortunately we will not support JS inside the files, so it'll be full static JS-less UI.

**Comment by sr229** [comment]
This relies on GH-3 being complete, so GH-3 must be complete first before we do UI.

**Comment by sr229** [comment]
Upon further investigation, AngleSharp's CSS renderer already handles most of the rendering for us, we just need to hook a driver, but this will still require GH-3.

**Comment by sr229** [comment]
Based on weeks of trial and error, I do believe we've reached a catch 22 so my recommendation would be using a mature runtime like [CefGlue](https://github.com/OutSystems/CefGlue).

**Comment by LeNitrous** [comment]
closing as moving to vignette
