### ISSUE TITLE
Epic: Simplify graphics API subsystem

### ISSUE THREAD

**Issue by sr229** [vignetteapp/sekai#54]
Currently our aim with the graphics API subsystem is to support as many devices as possible, but this comes with an additional cost that we must write new system-level APIs and abstract it over a high-level API. To reduce burden on Sekai's end post-Encore, we're exploring some avenues to simplify the graphics subsystem to achieve the following goals for Vignette:

- To create a single interface both engine-level and consumer-level (A game consuming Sekai through NuGet or a Vignette extension).
- Increase developer velocity by having one surface that =<2 developers could even maintain in a short notice.
- Share shader code with no need to write our own transpile (if possible).

## Option A: Re-visit [Veldrid](https://github.com/mellinoe/veldrid)
Currently @LeNitrous has expressed that we will re-visit Veldrid in some time in the future post-Encore, despite the friction Veldrid has given to us during the early days with Sekai's development. We're willing to give it a shot again since a lot has changed over the course of ~7 months.

## Option B: Evaluate [Dawn](https://dawn.googlesource.com/dawn/)

Dawn powers the WebGPU implementation of Chromium and implements a native API that wraps around Vulkan, DirectX, and even OpenGL. Dawn implements the WebGPU standard, which means we will be able to take advantage of the commonality of Web Standards. In fact, WebGPU-based APIs tend to be used by Rust-based projects using the `wgpu` crate as it is a common and standardized API over native graphics APIs, reducing maintenance overhead for anyone working with native graphics.

The Evergine team maintains a [WebGPU.NET](https://github.com/EvergineTeam/WebGPU.NET) library which is a 1-to-1 bindings with raw low level code, which is acceptable given that we will abstract this to be safer down the line as we usually do with our current implementation.

**Comment by LeNitrous** [comment]
Fixed in https://github.com/vignetteapp/sekai/commit/b46968233bc4fbff1365f14cb6d379d73e7e3537
